[build]
  command = "npm run install:hugo && npm run build"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.92.2_extended"
  NODE_VERSION = "20"
  PHP_VERSION = ""
  MISE_ENABLED = "false"
  # Add Hugo to PATH
  PATH = "/opt/buildhome/repo/node_modules/.bin:$PATH"
  
[build.image]
  name = "focal"