[build]
  command = "npm run build"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.92.2_extended"
  NODE_VERSION = "20"
  PHP_VERSION = ""
  MISE_ENABLED = "false"
  
[build.image]
  name = "focal"